language: generic
dist: xenial

branches:
    only: master

install: ./.ci/install.sh
script: ./.ci/build.sh

deploy:
    provider: releases
    overwrite: true
    skip_cleanup: true
    target_branch: master
    api_key: $GH_TOKEN
    file:
        - "./pandoc.css"
        - m.*
